# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michaelp/radar-sensor-board

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michaelp/radar-sensor-board

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michaelp/radar-sensor-board/CMakeFiles /home/michaelp/radar-sensor-board//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michaelp/radar-sensor-board/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named h523ceu6

# Build rule for target.
h523ceu6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 h523ceu6
.PHONY : h523ceu6

# fast build rule for target.
h523ceu6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/build
.PHONY : h523ceu6/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

#=============================================================================
# Target rules for targets named RTOS2

# Build rule for target.
RTOS2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RTOS2
.PHONY : RTOS2

# fast build rule for target.
RTOS2/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/RTOS2.dir/build.make cmake/stm32cubemx/CMakeFiles/RTOS2.dir/build
.PHONY : RTOS2/fast

Src/app_freertos.o: Src/app_freertos.c.o
.PHONY : Src/app_freertos.o

# target to build an object file
Src/app_freertos.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/app_freertos.c.o
.PHONY : Src/app_freertos.c.o

Src/app_freertos.i: Src/app_freertos.c.i
.PHONY : Src/app_freertos.i

# target to preprocess a source file
Src/app_freertos.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/app_freertos.c.i
.PHONY : Src/app_freertos.c.i

Src/app_freertos.s: Src/app_freertos.c.s
.PHONY : Src/app_freertos.s

# target to generate assembly for a file
Src/app_freertos.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/app_freertos.c.s
.PHONY : Src/app_freertos.c.s

Src/main.o: Src/main.c.o
.PHONY : Src/main.o

# target to build an object file
Src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/main.c.o
.PHONY : Src/main.c.o

Src/main.i: Src/main.c.i
.PHONY : Src/main.i

# target to preprocess a source file
Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/main.c.i
.PHONY : Src/main.c.i

Src/main.s: Src/main.c.s
.PHONY : Src/main.s

# target to generate assembly for a file
Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/main.c.s
.PHONY : Src/main.c.s

Src/spiglobalmap.o: Src/spiglobalmap.c.o
.PHONY : Src/spiglobalmap.o

# target to build an object file
Src/spiglobalmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/spiglobalmap.c.o
.PHONY : Src/spiglobalmap.c.o

Src/spiglobalmap.i: Src/spiglobalmap.c.i
.PHONY : Src/spiglobalmap.i

# target to preprocess a source file
Src/spiglobalmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/spiglobalmap.c.i
.PHONY : Src/spiglobalmap.c.i

Src/spiglobalmap.s: Src/spiglobalmap.c.s
.PHONY : Src/spiglobalmap.s

# target to generate assembly for a file
Src/spiglobalmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/spiglobalmap.c.s
.PHONY : Src/spiglobalmap.c.s

Src/stm32h5xx_hal_msp.o: Src/stm32h5xx_hal_msp.c.o
.PHONY : Src/stm32h5xx_hal_msp.o

# target to build an object file
Src/stm32h5xx_hal_msp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_msp.c.o
.PHONY : Src/stm32h5xx_hal_msp.c.o

Src/stm32h5xx_hal_msp.i: Src/stm32h5xx_hal_msp.c.i
.PHONY : Src/stm32h5xx_hal_msp.i

# target to preprocess a source file
Src/stm32h5xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_msp.c.i
.PHONY : Src/stm32h5xx_hal_msp.c.i

Src/stm32h5xx_hal_msp.s: Src/stm32h5xx_hal_msp.c.s
.PHONY : Src/stm32h5xx_hal_msp.s

# target to generate assembly for a file
Src/stm32h5xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_msp.c.s
.PHONY : Src/stm32h5xx_hal_msp.c.s

Src/stm32h5xx_hal_timebase_tim.o: Src/stm32h5xx_hal_timebase_tim.c.o
.PHONY : Src/stm32h5xx_hal_timebase_tim.o

# target to build an object file
Src/stm32h5xx_hal_timebase_tim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_timebase_tim.c.o
.PHONY : Src/stm32h5xx_hal_timebase_tim.c.o

Src/stm32h5xx_hal_timebase_tim.i: Src/stm32h5xx_hal_timebase_tim.c.i
.PHONY : Src/stm32h5xx_hal_timebase_tim.i

# target to preprocess a source file
Src/stm32h5xx_hal_timebase_tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_timebase_tim.c.i
.PHONY : Src/stm32h5xx_hal_timebase_tim.c.i

Src/stm32h5xx_hal_timebase_tim.s: Src/stm32h5xx_hal_timebase_tim.c.s
.PHONY : Src/stm32h5xx_hal_timebase_tim.s

# target to generate assembly for a file
Src/stm32h5xx_hal_timebase_tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_hal_timebase_tim.c.s
.PHONY : Src/stm32h5xx_hal_timebase_tim.c.s

Src/stm32h5xx_it.o: Src/stm32h5xx_it.c.o
.PHONY : Src/stm32h5xx_it.o

# target to build an object file
Src/stm32h5xx_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_it.c.o
.PHONY : Src/stm32h5xx_it.c.o

Src/stm32h5xx_it.i: Src/stm32h5xx_it.c.i
.PHONY : Src/stm32h5xx_it.i

# target to preprocess a source file
Src/stm32h5xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_it.c.i
.PHONY : Src/stm32h5xx_it.c.i

Src/stm32h5xx_it.s: Src/stm32h5xx_it.c.s
.PHONY : Src/stm32h5xx_it.s

# target to generate assembly for a file
Src/stm32h5xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/stm32h5xx_it.c.s
.PHONY : Src/stm32h5xx_it.c.s

Src/syscalls.o: Src/syscalls.c.o
.PHONY : Src/syscalls.o

# target to build an object file
Src/syscalls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/syscalls.c.o
.PHONY : Src/syscalls.c.o

Src/syscalls.i: Src/syscalls.c.i
.PHONY : Src/syscalls.i

# target to preprocess a source file
Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/syscalls.c.i
.PHONY : Src/syscalls.c.i

Src/syscalls.s: Src/syscalls.c.s
.PHONY : Src/syscalls.s

# target to generate assembly for a file
Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/syscalls.c.s
.PHONY : Src/syscalls.c.s

Src/sysmem.o: Src/sysmem.c.o
.PHONY : Src/sysmem.o

# target to build an object file
Src/sysmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/sysmem.c.o
.PHONY : Src/sysmem.c.o

Src/sysmem.i: Src/sysmem.c.i
.PHONY : Src/sysmem.i

# target to preprocess a source file
Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/sysmem.c.i
.PHONY : Src/sysmem.c.i

Src/sysmem.s: Src/sysmem.c.s
.PHONY : Src/sysmem.s

# target to generate assembly for a file
Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/sysmem.c.s
.PHONY : Src/sysmem.c.s

Src/xensiv_bgt60trxx.o: Src/xensiv_bgt60trxx.c.o
.PHONY : Src/xensiv_bgt60trxx.o

# target to build an object file
Src/xensiv_bgt60trxx.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx.c.o
.PHONY : Src/xensiv_bgt60trxx.c.o

Src/xensiv_bgt60trxx.i: Src/xensiv_bgt60trxx.c.i
.PHONY : Src/xensiv_bgt60trxx.i

# target to preprocess a source file
Src/xensiv_bgt60trxx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx.c.i
.PHONY : Src/xensiv_bgt60trxx.c.i

Src/xensiv_bgt60trxx.s: Src/xensiv_bgt60trxx.c.s
.PHONY : Src/xensiv_bgt60trxx.s

# target to generate assembly for a file
Src/xensiv_bgt60trxx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx.c.s
.PHONY : Src/xensiv_bgt60trxx.c.s

Src/xensiv_bgt60trxx_platform.o: Src/xensiv_bgt60trxx_platform.c.o
.PHONY : Src/xensiv_bgt60trxx_platform.o

# target to build an object file
Src/xensiv_bgt60trxx_platform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx_platform.c.o
.PHONY : Src/xensiv_bgt60trxx_platform.c.o

Src/xensiv_bgt60trxx_platform.i: Src/xensiv_bgt60trxx_platform.c.i
.PHONY : Src/xensiv_bgt60trxx_platform.i

# target to preprocess a source file
Src/xensiv_bgt60trxx_platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx_platform.c.i
.PHONY : Src/xensiv_bgt60trxx_platform.c.i

Src/xensiv_bgt60trxx_platform.s: Src/xensiv_bgt60trxx_platform.c.s
.PHONY : Src/xensiv_bgt60trxx_platform.s

# target to generate assembly for a file
Src/xensiv_bgt60trxx_platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/Src/xensiv_bgt60trxx_platform.c.s
.PHONY : Src/xensiv_bgt60trxx_platform.c.s

startup_stm32h523xx.o: startup_stm32h523xx.s.o
.PHONY : startup_stm32h523xx.o

# target to build an object file
startup_stm32h523xx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/h523ceu6.dir/build.make CMakeFiles/h523ceu6.dir/startup_stm32h523xx.s.o
.PHONY : startup_stm32h523xx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RTOS2"
	@echo "... STM32_Drivers"
	@echo "... h523ceu6"
	@echo "... Src/app_freertos.o"
	@echo "... Src/app_freertos.i"
	@echo "... Src/app_freertos.s"
	@echo "... Src/main.o"
	@echo "... Src/main.i"
	@echo "... Src/main.s"
	@echo "... Src/spiglobalmap.o"
	@echo "... Src/spiglobalmap.i"
	@echo "... Src/spiglobalmap.s"
	@echo "... Src/stm32h5xx_hal_msp.o"
	@echo "... Src/stm32h5xx_hal_msp.i"
	@echo "... Src/stm32h5xx_hal_msp.s"
	@echo "... Src/stm32h5xx_hal_timebase_tim.o"
	@echo "... Src/stm32h5xx_hal_timebase_tim.i"
	@echo "... Src/stm32h5xx_hal_timebase_tim.s"
	@echo "... Src/stm32h5xx_it.o"
	@echo "... Src/stm32h5xx_it.i"
	@echo "... Src/stm32h5xx_it.s"
	@echo "... Src/syscalls.o"
	@echo "... Src/syscalls.i"
	@echo "... Src/syscalls.s"
	@echo "... Src/sysmem.o"
	@echo "... Src/sysmem.i"
	@echo "... Src/sysmem.s"
	@echo "... Src/xensiv_bgt60trxx.o"
	@echo "... Src/xensiv_bgt60trxx.i"
	@echo "... Src/xensiv_bgt60trxx.s"
	@echo "... Src/xensiv_bgt60trxx_platform.o"
	@echo "... Src/xensiv_bgt60trxx_platform.i"
	@echo "... Src/xensiv_bgt60trxx_platform.s"
	@echo "... startup_stm32h523xx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

